# Database Configuration
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=HAU_StudentManagement;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=quy28102004
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# JPA/Hibernate Properties
# Đổi thành update để auto tạo schema nếu chưa có
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

# JWT Configuration
# Phải dài hơn 256 bits (32 ký tự)
app.jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
# Thời gian sống của token: 1 tuần (ms)
app.jwt.expiration=604800000

# Server Port
server.port=8080

# Logging
logging.level.org.springframework.security=DEBUG
